name: In My Dream Life
favicon: null
layout_spectrum: 0.00224
typography_spectrum: 0.3888296002987772
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f6cf'
    - '#6dcff6'
    - '#000000'
    - '#0086cd'
    - '#eb158f'
  brandStrength: 0.616399749647826
  lightness: 0.6915639371145517
  saturation: 0.9754274392034858
  rhythmicContrast: 0.9784310127142817
purpose: []
